### ISSUE TITLE
Add/update schema for Search API Solr to reflect new data type for hOCR indexing + Search Endpoint

### ISSUE THREAD

**Issue by giancarlobi** [esmero/strawberryfield#114]
The plugin to index MiniOCR/hOCR into Solr needs some configuration update regarding Search API Solr but also a schema update to avoid these status report errors:
![image](https://user-images.githubusercontent.com/4232178/100470944-8148cb00-30d9-11eb-87fa-21a022810210.png)

**Comment by DiegoPino** [comment]
Thanks. Yes, its a new type search API has no idea of. Will work on that!

**Comment by giancarlobi** [comment]
Also see this https://github.com/esmero/strawberryfield/pull/113#issuecomment-734397094

**Comment by giancarlobi** [comment]
@DiegoPino I'm not sure that yml settings are sufficient to add a new custom field type, probably we need a custom processor as stated here https://www.drupal.org/docs/8/modules/search-api/developer-documentation/create-custom-fields-using-a-custom-processor and I also found this interesting post https://drupal.stackexchange.com/questions/218129/how-to-add-a-custom-field-to-apache-solr.
Finally, I see that multivalue/singlevalue (we need single value for Solr plugin) has some issues and the last patch is since 16 days ago, see here: https://www.drupal.org/project/search_api_solr/issues/2906905#comment-13902770

**Comment by DiegoPino** [comment]
@giancarlobi means we need to use dev or patch?
I do not understand (yet) how Solr Search API provides internally its own basic field types/processors but I feel we can reuse this https://git.drupalcode.org/project/search_api_location/-/tree/8.x-1.x/src/Plugin/search_api/data_type
search_api_location provides a new Field type for Search API. Maybe we can borrow the same idea?

**Comment by DiegoPino** [comment]
Also, I have not read this but under https://www.drupal.org/node/2009760#add-data-type there is some logic that "may" make sense. Do you want us to explore this together?

**Comment by giancarlobi** [comment]
> @giancarlobi means we need to use dev or patch?

Not sure, probably we can achieve that (single value) without update to dev, I'm reading deeper the post.

> I do not understand (yet) how Solr Search API provides internally its own basic field types/processors but I feel we can reuse this https://git.drupalcode.org/project/search_api_location/-/tree/8.x-1.x/src/Plugin/search_api/data_type
> search_api_location provides a new Field type for Search API. Maybe we can borrow the same idea?

Uhm, that seems a little bit old, I will check deeper.

Also, I found here https://www.drupal.org/project/search_api_solr/issues/2906905#comment-13145549 how we can maps naming/field, that could be interesting in the case of ocr as we need something really custom for indexing MiniOCR

**Comment by giancarlobi** [comment]
> Also, I have not read this but under https://www.drupal.org/node/2009760#add-data-type there is some logic that "may" make sense. Do you want us to explore this together?

I saw that on Sunday (yes, Sunday) but I think (not sure, to check) it was before 4.x and we need instead to use custom processor as here https://www.drupal.org/docs/8/modules/search-api/developer-documentation/create-custom-fields-using-a-custom-processor

**Comment by giancarlobi** [comment]
> Do you want us to explore this together?

Yes, obviously, I'm not able without you to figure out this! Let me a couple of days to explore this and then we can talk about it on next out call, is this ok for you?

**Comment by giancarlobi** [comment]
Also, I found here https://www.drupal.org/project/search_api_solr/issues/2906905#comment-13145541 this, could be useful to know:

Or more elegant, use Drupal\search_api_solr\Utility\StreamingExpressionBuilder which translates into the real Solr field name:

  $builder->_field('foo');

**Comment by DiegoPino** [comment]
Implement since 2020
