### ISSUE TITLE
Cleanup file structure for deleted files

### ISSUE THREAD

**Issue by alliomeria** [esmero/strawberryfield#121]
# What is this? :bug:

When files are deleted from an ADO, and a certain key becomes empty (such as "image"), the corresponding file structures ("as:image") are sticking around even after the file deletion is saved. 

This issue may have been introduced near Beta3; Related to `strawberryfield` module.

**Comment by DiegoPino** [comment]
@alliomeria moved this to SBF since this modules handles the Persisting / Deleting files logic. Coding this now.

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/strawberryfield/commit/8faca1362ae8adcf61e3e84dbd3e09ea7b3f7377
