### ISSUE TITLE
Add SOLR SBF Flavor Document removal when File gets removed

### ISSUE THREAD

**Issue by DiegoPino** [esmero/strawberryfield#123]
# What?
When we remove a file, old SBR documents could end being left in Solr. We may want to remove them automatically (using the Solr tracker) when a node and/or file gets removed.

- Different ways of removing depending if the Node is removed v/s a File from a Node
 Important: Revision deletion triggers the same event as a full Node removal. Check that we do not remove everything if a revision is deleted.

**Comment by DiegoPino** [comment]
@pcambra I will assign this one to you but you can push back if you feel its is too complex/ you need a better understanding of the system to do this (so a few more weeks). This taps in Entity Hooks / Event Subscribers and Seach API tracker API.

This will also lead to using Frictionless data packages as a stable source of data generated by Strawberry runners for future reindexing instead of key/value approach (which I know its only temporary).  Let me know what you think tomorrow.

**Comment by pcambra** [comment]
@DiegoPino Maybe we could discuss about this one tomorrow? I wonder if the entities should not be marked to remove but this is probably more complex than I am thinking about :)

**Comment by pcambra** [comment]
@DiegoPino There's one edge case I'm not sure we should we dealing with or maybe it's dealt with already, when someone uploads a document and saves. Then realises they have uploaded the wrong document, so if they removed it after the queues are already in place, it will be indexed anyways. 
I was thinking in clearing the queues from here but feels wrong and scope creep, tbh. I think that should be the runners job, to check before indexing if the file actually exists in the context? `$references = file_get_file_references($file, NULL, EntityStorageInterface::FIELD_LOAD_CURRENT);`

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/strawberryfield/commit/a63f96807020f38fbd73e8096f47fb751090bbf1
