### ISSUE TITLE
Move from Identify to pdfinfo for PDFs

### ISSUE THREAD

**Issue by DiegoPino** [esmero/strawberryfield#125]
# why?

because Identify on PDFs is a bottleneck.

a PDF processed (all pages) to extract Page dimensions takes almost a minute (128 pages)
pdfinfo takes less than a second. 

The difference is HUGE.

Also, we already ship with `pdfinfo`

What needs to be done?

We need to have the same output format.

## Identify
`identify -format 'format:%m|width:%w|height:%h|orientation:%[orientation]@' -quiet  sbr_somehash.pdf`
Which gives us for each line this
`@format:PDF|width:628|height:790|orientation:Undefined` which we split and JSON-ify

## pdfinfo

We need first to get the number of pages (a few ms)
`pdfinfo  sbr_somehash.pdf -quiet  | grep "^Pages:"`
We get this
`Pages:          124`
Now with that number (needs processing we can call)
`pdfinfo sbr_somehash.pdf -f 1 -l 124 |grep 'Page'`
which will give us a large list of two lines per page
Page  124 size: 630 x 794 pts
Page  124 rot:  0

This is also in the `ms` range of processing time

## what is needed?

I have to change \Drupal\strawberryfield\StrawberryfieldFilePersisterService::getBaseFileMetadata
to exempt PDFs and Ghostscript files from run through identify and instead run PDF Info.

@giancarlobi I wonder if that is the case I should keep the same output formate we use of identify?
Or would it better to go for its own flv:pdfinfo?

**Comment by giancarlobi** [comment]
@DiegoPino Uhm ... probably more clean if we start with a new flv:pdfinfo. Also we can avoid to add `"format": "PDF",` and not sure if we need orientation too.
Can we imagine a jsonpatch to convert existing flv:identify ?

**Comment by DiegoPino** [comment]
Good call!. Yes. we can do that.

**Comment by DiegoPino** [comment]
I will also need to update all Twig templates we ship to ensure we are getting with from (both?) at the beginning and then deprecate identify for PDFs. Thanks!!

**Comment by DiegoPino** [comment]
Resolved via https://github.com/esmero/strawberryfield/commit/b70962c1e6fc1ac36b3e9b3927c4519a288584af
