### ISSUE TITLE
Add Ubuntu hydroponics compatibility

### ISSUE THREAD

**Issue by DiegoPino** [esmero/strawberryfield#131]
A few extra settings for users not using Docker for Hydroponics are needed.

**Comment by giancarlobi** [comment]
@DiegoPino I made in a my new brach changes to form and schema: https://github.com/giancarlobi/strawberryfield/tree/giancarlobi-RC1-Hpath

**Comment by giancarlobi** [comment]
ANd in a few minutes I'll pull also change to run hydroponics, then you can choose what better for us.

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/strawberryfield/commit/56014baa4d5df3a5a99b344b5c0b40e42528f3ec
