### ISSUE TITLE
Extend EntityJmesPathNameProvider to cover all supported Entities by Solr

### ISSUE THREAD

**Issue by DiegoPino** [esmero/strawberryfield#143]
# The story

We coded this cool thing a while. Allows IDs in the JSON to be casted into proper dynamic entity references and because of that Solr can then index all, including hierarchies, etc.

Right now its "hardcoded" for `node` entities, because we only really care for ADO to ADO relationships, but can be extended by adding an extra setting and some wrapper code to anything.

# The fix (super simple)

## Setting would go here:

https://github.com/esmero/strawberryfield/blob/1.0.0-RC2/src/Plugin/StrawberryfieldKeyNameProvider/EntityJmesPathNameProvider.php

And wrapper code here:

https://github.com/esmero/strawberryfield/blob/1.0.0-RC2/src/Plugin/Field/FieldType/StrawberryFieldItem.php#L175

Where instead of passing "node" we would pass the new setting, e.g taxonomy_term

As simple as that.

@patdunlavey @pcambra @alliomeria this would allow us to index into Solr more complex things. Not urgent right now but can be useful for people relaying on Taxonomies 

The list of things we can support is based on what Solr can index. So needs to come from this constant:

https://github.com/esmero/strawberryfield/blob/1.0.0-RC2/src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php#L33-L42, that said I may take that constant to some other place. Really not a good place live in.

**Comment by patdunlavey** [comment]
@DiegoPino are you suggesting this instead of the idea I  proposed on Friday of handling entity id references during presave by loading the entity and writing the values of its fields into the object JSON (e.g. taxonomy term name, description, custom fields)? If I understand what you are proposing, it would make storing these values in the ADO JSON potentially superfluous, and have a the advantage of being dynamic (e.g. if the price for a price bundle taxonomy term changes).

**Comment by patdunlavey** [comment]
@DiegoPino would you mind taking a look at the attached patch and tell me if I'm on the right track?
[issue-143.patch.txt](https://github.com/esmero/strawberryfield/files/5946900/issue-143.patch.txt)

**Comment by patdunlavey** [comment]
Here's an easier way to review: https://github.com/Born-Digital-US/strawberryfield/compare/1.0.0-RC2...Born-Digital-US:issue-143?expand=1

**Comment by DiegoPino** [comment]
Hi @patdunlavey its looking good. I just pushed a branch for you that has the schema change and an update hook.
https://github.com/esmero/strawberryfield/tree/ISSUE-143
Let me give you some code ideas on your branch and you can then make a pull to this one. Give me a minute

**Comment by DiegoPino** [comment]
Some reviews: (no preview sadly because there is no pull yet)

Here: https://github.com/Born-Digital-US/strawberryfield/compare/1.0.0-RC2...Born-Digital-US:issue-143?expand=1#diff-b0e23320c8fd948a032beb598089e9e8179c6d3cf897f284fca9004a2bad08a9R49

We are not going to support all entities. We have for now a subset here: https://github.com/esmero/strawberryfield/blob/main/src/EventSubscriber/StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator.php#L33

Those are of course not "select box" ready. But being a constant (which we may move later in another pull to a different more central part) makes all more consistent. Also Solr can not Index everything.
To match other Drupal configs around change `source_entity_type` to simply `entity_type` (its also like that In the changed schema)

```PHP
 $element['entity_type'] = [
      '#id' => 'entity_type',
      '#type' => 'select',
      '#title' => $this->t('Entity type.'),
      '#options' => array_combine($entity_types, $entity_types),
      '#default_value' => !empty($this->getConfiguration()['entity_type']) ? $this->getConfiguration()['entity_type'] : 'node',
      '#description' => $this->t('The Drupal entity type'),
      '#required' => true,
    ];
```

- https://github.com/Born-Digital-US/strawberryfield/compare/1.0.0-RC2...Born-Digital-US:issue-143?expand=1#diff-7241895abe8923ec1a1e8eb7e9406a99373c5dc2c91063129620dc30f91612feR146 

This is good! I was thinking hard about the many ways we could pass the config options down and your solution works for me. We may to refactor in the future to reuse the `$keynamelist[$processor_class]` as single structure to pass $property, the $keys and the $configs. That way we save a few bytes of memory but I like your approach. Current implementation checks but it would be nice to depend more on the output of  $plugin_instance->provideKeyNames($entity_id) instead of the actual`exposed_keys`, those will many times match the exposed $properties, (e.g https://github.com/esmero/strawberryfield/blob/1.0.0-RC2/src/Plugin/StrawberryfieldKeyNameProvider/JmesPathNameProvider.php#L99) but sometimes not, like here
https://github.com/esmero/strawberryfield/blob/1.0.0-RC2/src/Plugin/StrawberryfieldKeyNameProvider/JsonldKeyNameProvider.php#L99
Where each exposed key is really the actual JSON key. This affects us not really in our current implementation but we will want to do more with this plugins in the future!

Go ahead and make the pull against ISSUE-143, code reviews are easier on an open pull.

**Comment by DiegoPino** [comment]
I also assigned you =)

**Comment by DiegoPino** [comment]
@patdunlavey I opened a follow up ISSUE for the many entity references issue at #146

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/strawberryfield/commit/026847c1210e18d60e5c76c21f75f62a4d8a2633
