### ISSUE TITLE
Add 'group' to supported entity types?

### ISSUE THREAD

**Issue by patdunlavey** [esmero/strawberryfield#145]
The [drupal/group](https://www.drupal.org/project/group) module, which we are planning to use for Partners in CAR, is not among the supported entity types in `\Drupal\strawberryfield\EventSubscriber\StrawberryfieldEventPresaveSubscriberAsFileStructureGenerator::SUPPORTED_CORE_ENTITIES`. For the purposes of solr indexing this could be useful. Is this hard to do? Can you provide some pointers, @DiegoPino (beyond the obvious of adding 'entity:group' to that list).

**Comment by DiegoPino** [comment]
@patdunlavey I really do not know how Groups work. Are Standard Drupal `user` entity attached to the groups? If so just having the user (owner, core drupal no change here) will allow you to index directly any related entities/labels (if Solr supports that).Also, what group specific data are you storing inside the JSON? I would guess group information is attached to the Node itself, not the metadata, so even if you can (that obvious change) I do not see how group info may end inside the JSON at all. 

We can discuss this need deeper tomorrow on our call and do some screen sharing and live edit code to solve the use case better.

**Comment by patdunlavey** [comment]
I was thinking of an entity reference field to the group in the metadata webform, but that does not make sense when I think about it. Closing.
