### ISSUE TITLE
Make EXIF extraction configurable

### ISSUE THREAD

**Issue by DiegoPino** [esmero/strawberryfield#190]
# What?

Users will want to have custom exif tags based on their needs:

eg. in https://github.com/esmero/webform_strawberryfield/issues/71
@mlohnash says:

> Hi Diego,
> 
> Here is the information requested. 
> 
> This is the exif tool formula run on incoming tif, jpg, and pdf files from our vendors:
> exiftool -csv -r -FileType -Compression -PhotometricInterpretation -ColorSpaceData -XResolution -YResolution -BitsPerSample -Date -Description-en -Source -Title-en -Rights-en -G4 [drive/folder]>[desination .csv file]
> 
> I have attached an example of how we use this information to verify files received
> ( [winter18_HDD-164_techout.xlsx](https://github.com/esmero/webform_strawberryfield/files/6689464/winter18_HDD-164_techout.xlsx) ) conform to our statement of work ( [CA-R_SOW2020_PT(3).pdf](https://github.com/esmero/webform_strawberryfield/files/6689466/CA-R_SOW2020_PT.3.pdf) - our requirements are laid out on page 3). 
> 

Approach will to add extra settings for EXIF to allow additional/less/more tags/options to be passed to exiftool. Also an exiftool/mediainfo binary based strawberry runner will be added as a config.

Additional setting for all Technical Metadata extraction (File Size Limit for real time processing) will be added. That way very large (Gigabyte size) will be skipped and taken by the background processor to avoid delays during uploads.

**Comment by DiegoPino** [comment]
@alliomeria 👀

**Comment by alliomeria** [comment]
Hello @DiegoPino, following up to drop off the notes related to the recent Archipelago Slack conversation with Stuart (hi :) and thank you!). To recap, Stuart reached out to ask about IPTC Keywords that were not appearing in the extracted exif upon ingest into Archipelago.

Solution: add `"-keywords*"` [here](https://github.com/esmero/strawberryfield/blob/69c1c4e7e44572a548ba6374731f4db66976f295/src/StrawberryfieldFileMetadataService.php#L333) like so:
`        $exec_path . ' -json -q -a -gps:all -Common "-gps*" "-keywords*" -xmp:all -XMP-tiff:Orientation -ImageWidth -ImageHeight -Canon -Nikon-AllDates -pdf:all -ee -MIMEType ' . $templocation_for_exec,
`

**Comment by DiegoPino** [comment]
@alliomeria thanks. I will start by making these the defaults but then follow up with a config option.
 Thanks again

**Comment by alliomeria** [comment]
Thank you @DiegoPino, sounds great! :)

**Comment by DiegoPino** [comment]
@alliomeria I added a commit to my open, larger pull request bringing your code there. https://github.com/esmero/strawberryfield/commit/caeb317c4c80697ace43bfa5ebb111e5adcd3316
I will add attribution (as co-author) when merging!
