### ISSUE TITLE
Change frictionlessdata/datapackage version to dev-main in composer.json

### ISSUE THREAD

**Issue by patdunlavey** [esmero/strawberryfield#195]
# What?

Attempting to composer update archipelago-deployment with `"strawberryfield/strawberryfield": "dev-1.0.0-RC3",` results in a composer error:
```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires strawberryfield/strawberryfield dev-1.0.0-RC3 -> satisfiable by strawberryfield/strawberryfield[dev-1.0.0-RC3].
    - strawberryfield/strawberryfield dev-1.0.0-RC3 requires frictionlessdata/datapackage dev-master -> found frictionlessdata/datapackage[dev-main, dev-ISSUE-43, v0.1.0, ..., v0.1.9, v1.0.0] but it does not match the constraint.
  Problem 2
    - strawberryfield/strawberryfield dev-1.0.0-RC3 requires frictionlessdata/datapackage dev-master -> found frictionlessdata/datapackage[dev-main, dev-ISSUE-43, v0.1.0, ..., v0.1.9, v1.0.0] but it does not match the constraint.
    - strawberryfield/strawberry_runners 0.2.0.x-dev requires strawberryfield/strawberryfield dev-1.0.0-RC3 -> satisfiable by strawberryfield/strawberryfield[dev-1.0.0-RC3].
    - Root composer.json requires strawberryfield/strawberry_runners 0.2.0.x-dev -> satisfiable by strawberryfield/strawberry_runners[0.2.0.x-dev].
```

I assume this came about because the branch "frictionlessdata/datapackage dev-master" was recently renamed "dev-main".

# Proposed solution
Change [Line 23](https://github.com/esmero/strawberryfield/blob/1.0.0-RC3/composer.json#L23) to 
```
        "frictionlessdata/datapackage": "dev-main",
```

# Also
The same change needs to be made in any other composer.json files that require `"frictionlessdata/datapackage": "dev-master"`. These include [archipelago-deployment](https://github.com/esmero/archipelago-deployment/blob/1.0.0-RC2/composer.json#L82) and [archipelago-deployment-live](https://github.com/esmero/archipelago-deployment-live/blob/1.0.0-RC2/drupal/composer.default.json#L82)

**Comment by DiegoPino** [comment]
@patdunlavey yes, working on this already. We made the change in frictionless last week (I'm maintaining the package) and I'm preparing now the updated json files. Sadly we could not preserve the old `masters` as alias so this is backwards breaking. Fixes will be applied to all branches before 16:00. Thanks for reporting

**Comment by patdunlavey** [comment]
Great! I'll stop writing tickets for archipelago-deployment and archipelago-deployment-live! ;-)

**Comment by DiegoPino** [comment]
@patdunlavey this is not the last time this may happen with any PHP library that decides to move their branches. I have almost every pulls ready for merging testing and this sadly opened a larger regression issue all around the board.

That said, if you ever run on this issue with any other not by us managed package where updating the code is not possible,

do the following (using this same package as an example)

composer require frictionlessdata/datapackage:"dev-main as dev-master" strawberryfield/strawberryfield: "dev-1.0.0-RC3"  

Which will alias `dev-main` as `dev-master` and will allow the dependency to match whatever the demanding packages needs.

**Comment by DiegoPino** [comment]
Marking this as fixed. RC3, RC1 and RC3 have been retroactively fixed (in the branches, can't touch the actual releases so part of the trade here). archipelago-deployment and archipelago-deployment-live have all also been update. Thanks
