### ISSUE TITLE
Create Strawberry Field Documentation

### ISSUE THREAD

**Issue by Favenzio** [esmero/strawberryfield#2]
At our NYC summit we came up with a set of requirements for Strawberry Field:

- Ability to Add a Field of type "Strawberry Field" to Content Type.
- Make JSON elements available to other Drupal modules.
- Allow Admin users to specify for each instance of a Strawberry Field (field settings) alternate representations of JSON data.
- Make alternate representations of JSON (JSON-LD) available to other modules.
- Ability for Admin users to choose how to edit field:
    - Form user submitted from
    - "omni" form: All values hydrated
    - Raw JSON (indented/color coded would be nice)

At some point we will need to formalize these requirements and create documentation for module usage.

**Comment by DiegoPino** [comment]
Closed, fixed so long ago
