### ISSUE TITLE
Open range edtf dates cause errors when indexing

### ISSUE THREAD

**Issue by patdunlavey** [esmero/strawberryfield#207]
The problem:

Set a date with the value "../1800" (open range date with no start date) then try to index it as a date. You'll get an error:
```
Error: Call to a member function getMin() on null in EDTF\Model\Interval->getMin() (line 58 of /var/www/html/vendor/professional-wiki/edtf/src/Model/Interval.php).
```
This is because when the string is parsed, the returned object is an interval date with no start date. getMin on an interval date tries to getMin on the start date, which is null, throwing the error.

A solution is to check the class of edtf date that is returned by parsing, and if an interval date, first check to see if hasStartDate() (and hasEndDate()) before running getMin.

A PR to fix this will follow!

**Comment by DiegoPino** [comment]
I see.. mmm..good catch! 🥼  I mean... how much EDTF do you all use? every possible variation?? Gosh. Will wait for the pull and this needs to go into the release so please hurry! 😆

**Comment by patdunlavey** [comment]
PR created: https://github.com/esmero/strawberryfield/pull/208

**Comment by DiegoPino** [comment]
@patdunlavey so this is a bug in EDTF?

Because the constructor for the Interval type does not allow a NULL start nor end? (of type IntervalSide) ?

```PHP
class Interval implements EdtfValue {
	use CoversTrait;

	public const NORMAL = 0;
	public const OPEN = 1;
	public const UNKNOWN = 2;

	private IntervalSide $start;
	private IntervalSide $end;
	private ?int $significantDigit;
	private ?int $estimated;

	/**
	 * @throws InvalidArgumentException
	 */
	public function __construct(
		IntervalSide $start,
		IntervalSide $end,
		?int $significantDigit = null,
		?int $estimated = null
	) {
		$this->start = $start;
		$this->end = $end;
		$this->significantDigit = $significantDigit;
		$this->estimated = $estimated;

		$this->assertAtLeastOneSideIsNormal();
		$this->assertEndIsLaterThanStart();
	}

	private function assertAtLeastOneSideIsNormal(): void {
		if ( !$this->start->isNormalInterval() && !$this->end->isNormalInterval() ) {
			throw new InvalidArgumentException( 'Interval needs to have one normal side' );
		}
	}

	private function assertEndIsLaterThanStart(): void {
		if ( $this->hasStartDate() && $this->hasEndDate() ) {
			// TODO: refactor to earlierThan/laterThan methods on ExtDate
			if ( $this->getStartDate()->getMax() >= $this->getEndDate()->getMin() ) {
				throw new InvalidArgumentException( 'The precision of dates in a set range needs to be the same' );
			}
		}
	}
```

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/strawberryfield/commit/afdea67fac4187cdbaebadacaea62d22f4848399
Thanks @patdunlavey !
