### ISSUE TITLE
Add more Processing Options to JMESPath based KeyName providers

### ISSUE THREAD

**Issue by DiegoPino** [esmero/strawberryfield#224]
# What?

New options need to be 
- Normalize Strings
  - Lower Case
  - Title Case  
  - Trim spaces
- Date Granularity Deduplication (like if a date is a single day, the start/end date will be the same but different hours. Indexing 2 dates eventually
- Date Range (Drupal way) to allow Native date Range to be indexed into Solr
 
@patdunlavey @aksm @alliomeria @karomabiles any other data/string manipulations we need before sending the JSON keys data into Solr?

**Comment by patdunlavey** [comment]
For date range indexing in solr, I'm thinking two things would be needed:
1. In https://github.com/esmero/strawberryfield/blob/1.4.0/src/Plugin/StrawberryfieldKeyNameProvider/JmesPathNameProvider.php, add a checkbox to appear in the JmesPath Strawberry Field Key Name Provider configuration that would appear after the user clicks "Is Date?" that would read (something like) "Generate as Date Range (Check this option if  - AND ONLY IF - you plan to index this value as a date range in solr.)"
2. Here: https://github.com/esmero/strawberryfield/blob/1.4.0/src/Plugin/DataType/StrawberryValuesViaJmesPathFromJson.php#L170, after all the processes have generated a list of dates, check to see if the date_range option was checked in the configuration, and if so, winnow $values down to min and max, and then replace the two $values with an object with `:value` and `:end_value` (see [`search_api_solr\Plugin\search_api\processor\DateRange::preprocessIndexItems`](https://git.drupalcode.org/project/search_api_solr/-/blob/4.x/src/Plugin/search_api/processor/DateRange.php?ref_type=heads))

**Comment by DiegoPino** [comment]
exactly. That's the key

**Comment by patdunlavey** [comment]
The more I look at Drupal's date range situation, the more I worry that trying to index dates as solr date ranges and then trying to facet or search in Drupal will lead us down a trail of tears. Rosie created a nice summary [here](https://docs.lefaive.ca/wiki/Dates_in_Drupal_and_Solr). Islandora's [controlled_access_terms](https://github.com/Islandora/controlled_access_terms) module's "EDTFYear" search_api processor (`Plugin\search_api\processor\EDTFYear::addFieldValues`) handles the date range indexing problem at a one-year granularity by actually [indexing every year in the date range](https://github.com/Islandora/controlled_access_terms/blob/2.x/src/Plugin/search_api/processor/EDTFYear.php#L211).

I'm guessing that you reached a similar conclusion @DiegoPino: that "there be dragons" going down the solr date range path?

**Comment by DiegoPino** [comment]
@patdunlavey thanks for sharing. I don't think our way should be that. We are already indexing start/end ranges for EDTF dates as multiples values without iterating in-between using native ETDF processing. That is enough for an actual facet range query (facet range data queries don't need a range Solr date field, we have tested and with granularity it is fast/promising). the only real benefit of using a native date range really is for compatibility and also cases where you have gaps. e.g 1910-1960, 1970-1990. In that case our approach might confuse a range query by allowing 1965... (but maybe.. not even sure it will happen).

**Comment by DiegoPino** [comment]
Also @patdunlavey as a side note. We have repositories with data that spans from 1600-1980... a single ADO. Like indexing every year in between is not a great idea / dangerous. My real concern is the lack of checks on the Search API part that might lead to human induced errors that are hard to recover for users. Not the actual -our side of- code things

**Comment by patdunlavey** [comment]
Thanks @DiegoPino - more to think about!

**Comment by patdunlavey** [comment]
I decided to see what would happen if I implemented solr date range indexing like I [described](https://github.com/esmero/strawberryfield/issues/224#issuecomment-2375169062). Unfortunately, I quickly ran into trouble during indexing. I added this at line 170 [here](https://github.com/esmero/strawberryfield/blob/bc567d106f3ff52654a213cdf72f608dd2195cd3/src/Plugin/DataType/StrawberryValuesViaJmesPathFromJson.php#L170):
```
        if ($date_range && !empty($values)) {
          // Get min and max dates from the $values array
          $min = min($values);
          $max = max($values);
          $values = [new DateRangeValue($min, $max)];
        }
```
The search api field is set to "Date Range" to match the settings for the strawberry key name provider (the `$date_range` variable) ...but when I try to index an object with a date range, I am getting 
```
StatusText: 500 Service unavailable (with message)
ResponseText: The website encountered an unexpected error. Try again later.Error: Object of class Drupal\search_api_solr\Plugin\search_api\data_type\value\DateRangeValue could not be converted to string in Drupal\search_api\Plugin\search_api\data_type\DateDataType->getValue() (line 41 of modules/contrib/search_api/src/Plugin/search_api/data_type/DateDataType.php). Drupal\search_api\Item\Field->addValue(Object) (Line: 189)
Drupal\search_api\Utility\FieldsHelper->extractField(Object, Object) (Line: 148)
Drupal\search_api\Utility\FieldsHelper->extractFields(Object, Array, 'en') (Line: 169)
Drupal\search_api\Utility\FieldsHelper->extractFields(Object, Array, 'en') (Line: 275)
Drupal\search_api\Item\Item->getFields() (Line: 180)
Drupal\search_api\Plugin\search_api\processor\RenderedItem->addFieldValues(Object) (Line: 281)
Drupal\search_api\Item\Item->getFields() (Line: 987)
Drupal\search_api\Entity\Index->indexSpecificItems(Array) (Line: 935)
Drupal\search_api\Entity\Index->indexItems(50) (Line: 160)
Drupal\search_api\IndexBatchHelper::process(Object, 50, -1, Array) (Line: 296)
```
I don't understand why it's calling Drupal\search_api\Plugin\search_api\data_type\DateDataType->getValue().  I'll get a PR up tomorrow so you maybe you can see what I'm doing wrong.

**Comment by DiegoPino** [comment]
Hi Pat, the key name provider needs to mimic a vanilla date range drupal
field object data type structure. Without seeing the code is suspect you
are transforming it somehow already into  the search api version (which at
a field property level) is unexpected and really is what search api (or a
processor) already does

Will keep an eye on your pull. Night

**Comment by DiegoPino** [comment]
@patdunlavey give me 30 minutes and I share a snippet of code for you that does work.
It does work BUT just a caveat ... imagine the following data reality

- JSON KEY (date_created) contains multiple values .... an EDTF exact RANGE, a single EDTF DATE an Approximate EDTF Date...
- Each one of these will be processed via ETDF ending in multiple date range objects...(before being exposed as a Strawberry Field Property, via the new code and search API creating its own proxy object just to finally convert it into a string). So in Solr, IF All goes right ..  the "single EDTF DATE" will be expressed as a whole day, from midnight to 23:59... So. 

The question here is, do we just blindly assume the data coming from the user ends in Solr as SUCH, or do we need to do date math to only index ranges or even more, try to find the commonalities and remove any overlaps and only generate multiple values when there are gaps?

Anyhow ... give me 30!

**Comment by patdunlavey** [comment]
Thank you! For what it's worth, here's the stuff I've been trying: https://github.com/esmero/strawberryfield/compare/main...Born-Digital-US:strawberryfield:issues/224-index-date-ranges?expand=1

**Comment by patdunlavey** [comment]
Responding to your question - I _think_ the behavior I expect is that each EDTF date is indexed as a date range (mind-blowing realization: ALL EDTF dates are inherently fuzzy - i.e. can be understood to express a range), with the additional understanding that if the EDTF date expression includes a set of dates, that each date in the set is indexed separately as a date range. I _think_ this is what comes out of the EDTF date processing - i.e. each date expressed in an EDTF expression emerges as a `$values` array. If that understanding is correct, then no, no further logic is required. We just process each `$values` array, get the min/max, and index that as a date range. But, boy, I could be wrong about this!!

**Comment by DiegoPino** [comment]
Hi @patdunlavey still on this. Need to debug a bit to make sure I don't hit exceptions.

**Comment by DiegoPino** [comment]
@patdunlavey this stuff is hard. Basically all morning. It seems that the way the DateRange processor expects/extracts the values assumes a different nesting... like all "value" in an array, all '"end_value" in another instead of a list of [value,end_value] pairs.
Because I am failing here with a similar error as your last one and honestly need **more time** (hours) to figure out where the date to INT is happening. Sorry

**Comment by DiegoPino** [comment]
![image](https://github.com/user-attachments/assets/c7603dab-838e-49d0-a770-bef503ee60d6)
Look, The native stuff acts more like a different type of "item" element with sub properties ... which probably means for the date_range case we can't use a listItem as such, we need initiate a data type the way we use the Entity Reference Key Name provider but the native Drupal type... ufff

**Comment by DiegoPino** [comment]
The reason @patdunlavey this is not working is

/**
 *
 * Flavor Strawberry Field Key Name Provider
 *
 * @StrawberryfieldKeyNameProvider(
 *    id = "jmespath",
 *    label = @Translation("JmesPath Strawberry Field Key Name Provider"),
 *    processor_class = "\Drupal\strawberryfield\Plugin\DataType\StrawberryValuesViaJmesPathFromJson",
 *    item_type = "string"
 * )
 */
 
 item_type is what defines the native data structure. This Drupal ranges are NOT that...

**Comment by patdunlavey** [comment]
Ufff is right! Thank you for deep-diving into this!! It sounds like solving this would require a lot of time/code - and unfortunately, this is well over my head, so that solution would probably not come from me. The hacky solution of just indexing every year between start and end is looking a lot more sane!

**Comment by DiegoPino** [comment]
Hey Pat, I am on it, but I still don’t understand the need for indexing dates in between. What are you trying to accomplish you can't with current approach we have? The all dates in-between is not something I will implement in Archipelago, for dates in the wild (we have archeological things, colonial times things) it is non scalable.

If you explain the use case pretty sure I will understand better

Thanks!

**Comment by patdunlavey** [comment]
I think my use case is common:
I have an object with whose origin date (say) is "19XX" (somewhere between 1900-01-01T00:00:00 and 1999-12-31T25:59:59). Now I want to search for origin dates for (that [_intersect_](https://solr.apache.org/guide/6_6/working-with-dates.html#WorkingwithDates-MoreDateRangeFieldDetails)) the year "1950" - i.e. `origin_date:["1950-01-01" TO "1950-12-31"]`. Indexed as a date, we would have two values for this object in solr: "1900-01-01T00:00:00" and "1999-12-31T25:59:59". The query `origin_date:["1950-01-01" TO "1950-12-31"]` finds nothing.

**Comment by DiegoPino** [comment]
mmm.. that query should work with the current implementation .. give me a little while, going into a call.

**Comment by patdunlavey** [comment]
I tested your belief that this query should work by doing the following:
- I have an object with an originInfo record with start date = "1836" and end date = "1886"
- This is indexed in solr (regular date field) as four values, as seen in the results from this query: `its_nid:125554 AND dm_origininfo_dates:*`, like this:
```
dm_origininfo_dates: [
"1836-01-01T04:56:00Z",
"1837-01-01T04:55:59Z",
"1886-01-01T05:00:00Z",
"1887-01-01T04:59:59Z"
],
```
- But if I run the query adding a date value range condition of 1850 to 1860: `its_nid:125554 AND dm_origininfo_dates:["1850-01-01T00:00:00Z" TO "1860-01-01T00:00:00Z"]`, I get zero results.

**Comment by DiegoPino** [comment]
@patdunlavey this is a data issue in your indexing strategy (or in the source data, or how you expose the values to Drupal via the keyname providers). A key name provider will only read a list of values. And each individual entry there is not an EDTF range.

If the processed (by the keynameprovider) JMESPATH was instead
`["1836-01-01/1886-01-01"]`
or
`["1836-XX-XX/1886-XX-XX"]`
The JMESPATH date processor would know what do to,
but just sending two values will be processed as an array of two point values. When it reaches the Processor the actual keys
(start and end) are gone already

If that is the shape of your data... and assuming you know that both start and end ARE indeed correct ISO dates (and or can be parsed by EDTF if you concatenate them)...

Your JMESPATH driving the key name provider could be modified to generate a valid EDTF range string ...

here is an example

Given:

```JSON
{
 "date_created_edtf": {
        "date_type": "date_range",
        "date_from": "1999-10-02",
        "date_to": "2024-10-18",
        "date_free": ""
    }
}
```
A possible JMESPATH could be  (try it on the ADO tools)

`[date_created_edtf][?"date_type" == 'date_range'][ join('/',[date_from,date_from])][]`

**Comment by DiegoPino** [comment]
@patdunlavey please let me know if that does (or not) solve the issue. The reason I ask is because the date facets (with a range) right now do a send a &fq={!tag%3Dfacet:date_created_original}dm_date_created_original:["1999-10-02T00:00:00Z"+TO+"2024-10-02T23:59:59Z"] and I am getting hits ... so either we have been doing this wrong since the beginning or not sure what else is happening. Still working on the code though for native ranges (and you will still need that JMESPATH for that ...)

**Comment by patdunlavey** [comment]
I'll dig into it tomorrow morning (almost end-of-day here). We're using a very customized widget for editing originInfo blocks (client is very into MODS, and ability to import/export without losing anything), so the json data is quite different than out of the box archi. That said, I should be able to adapt my JMESPath expressions to create EDTF range strings instead of start and end dates for the purpose of the key name provider and solr indexing.

**Comment by patdunlavey** [comment]
@DiegoPino I just saw your new [PR](https://github.com/esmero/strawberryfield/pull/335) come in - ignore the previous comment! I'll give that a whirl right now!

**Comment by DiegoPino** [comment]
@patdunlavey yes. I mean the new code allows the native Range now, but with the normal date (multiple dates), given this data in Solr

"dm_date_created_original":["1960-01-01T05:00:00Z",
          "1961-01-01T04:59:59Z",
          "1961-12-01T05:00:00Z",
          "1962-01-01T04:59:59Z",
          "1977-01-01T05:00:00Z",
          "2024-01-01T04:59:59Z"]},

For this query


dm_date_created_original: [1960-01-01T05:00:00Z TO 1990-01-01T05:00:00Z]

I am getting a hit? Those are dates in-between. But yeah, from 1980 to 1990 I don't get anything bc of the gaps... So really... this is related to the fact that Multiple dates will generate `gaps` in the way Solr processes them. (of course when not using the new date range processor and index as native date range too). Still the new date range field requires you to be super aware of not having gaps neither

**Comment by DiegoPino** [comment]
FYI: those same values generate these ranges
```
"drm_date_as_range":["[1977-01-01T05:00:00Z TO 2024-01-01T04:59:59Z]",
          "[1960-01-01T05:00:00Z TO 1961-01-01T04:59:59Z]",
          "[1961-12-01T05:00:00Z TO 1962-01-01T04:59:59Z]"],
          ```
