### ISSUE TITLE
Composer won't delete base file names I considered unsafe (weird issue)

### ISSUE THREAD

**Issue by DiegoPino** [esmero/strawberryfield#265]
# What?

So this is not really an issue. I mark files that start with a `.` and end with `.php` etc as unsafe to be composted. We have seen an Archipelago not composting lately, happens that all files being remotely downloaded are of this type `..myfile.pdf`

I would dispute the file naming convention here (a lot) but the fact is we need to compost these.
So, I need ideas/solutions.

Lower the security? Do it differently?

The code is here:

https://github.com/esmero/strawberryfield/blob/573ffa44a369ad68c59a92b2746258c2671ef13f/src/Plugin/QueueWorker/CompostQueueWorker.php#L218-L236

@alliomeria and @karomabiles  this affects you directly
@aksm ideas? (other than removing the [.] as unsafe)

**Comment by aksm** [comment]
@DiegoPino Is it possible to do an override for file name patterns that are ok to delete?

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/strawberryfield/commit/041183e535d985824721aba2d87a4d896030fc0c
