### ISSUE TITLE
Upgrade EDTF PHP library from 2.0.2 to 3.0.0

### ISSUE THREAD

**Issue by aksm** [esmero/strawberryfield#276]
# What?
Corresponding issue to esmero/archipelago-deployment#250.

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/strawberryfield/commit/ce448a0ebe16650df19708459a4600d2c4d2c9e1
This will allow us to ship with alternate-not default language translations (like spanish) and avoid the wrong Language strategy used by default (ordinals in English) by 2.x
