### ISSUE TITLE
When to use strawberryfield_voc_id?

### ISSUE THREAD

**Issue by fishfree** [esmero/strawberryfield#285]
I notice the vocabulary on page `/admin/structure/taxonomy/manage/strawberryfield_voc_id/overview`. How does it work? When to use it? I cannot figure it out.

**Comment by DiegoPino** [comment]
It keeps track of every json key (path/hierarchical) ever ingested into your repository. How to use it is really up to you. You can even delete it and it will be recreated on the next ingest

**Comment by DiegoPino** [comment]
@fishfree will close this one since this is more like a question than an issue. Also, maybe you want to join our Slack for more like support/how to questions? Thanks!
