### ISSUE TITLE
accessCheck needed in \Drupal\strawberryfield\StrawberryfieldFilePersisterService::removeUsageFilesInJson

### ISSUE THREAD

**Issue by patdunlavey** [esmero/strawberryfield#294]
Starting to work on my D10.1 upgrade and I hit the \Drupal::entityQuery accessCheck error here:
https://github.com/esmero/strawberryfield/blob/ff229bb45864d6438a053d3921290c27b8192bc0/src/StrawberryfieldFilePersisterService.php#L1083

To fix this, just need to change that line to
```
            )->accessCheck(FALSE)->execute();
```
(I'm presuming that since there was no pre-existing accessCheck, that the correct value should be `FALSE`.)

**Comment by DiegoPino** [comment]
hu! I thought I had caught all of those? Yes false is Ok. Wonder why none of the repos have complaint about this already. Thanks! Want me to make the pull or you ready for an 1.3.0 pull right now? thanks!!!

**Comment by patdunlavey** [comment]
If you don't mind doing it, it will be fewer steps. Thanks.

**Comment by DiegoPino** [comment]
Got it! Thanks for reporting

**Comment by DiegoPino** [comment]
@patdunlavey can you check/approve both pulls? Thanks again!

**Comment by DiegoPino** [comment]
Solved. Thanks @patdunlavey
