### ISSUE TITLE
Create config for the Solr field used in Type/View Mode mapping 

### ISSUE THREAD

**Issue by marlo-longley** [esmero/strawberryfield#53]
### What is needed?

Right now we can configure ADO by Type to map onto View Modes in Drupal.
See: `/admin/config/archipelago/viewmode_mapping` in an Archipelago instance.

Solr field for Type is fixed/hardcode currently.
See [here](https://github.com/esmero/format_strawberryfield/blob/8.x-1.0-beta1/src/Form/ViewModeMappingSettingsForm.php#L226). 

Tasks:
1. Make a config form that allows user to set which Solr Server, Index, and then Field will be used in the ADO Type/View Mode mapping. 
2. And then change the `ViewModeMappingSettingsForm` to draw from this config, rather than hardcode.

#### Notes
I need to think about naming for this. It's kind of clunky. I started using "Type to Solr Field" for the name of the form which probably isn't clear.

**Comment by DiegoPino** [comment]
Partially Solved via https://github.com/esmero/strawberryfield/commit/30fd84f3541dc52cf02cb6165511266dd25d853c
Will do the format_strawberryfield pull now to close the circle

**Comment by aksm** [comment]
@DiegoPino was this circle ever closed?

**Comment by DiegoPino** [comment]
Please check the source code

**Comment by DiegoPino** [comment]
Fixed
