### ISSUE TITLE
Add an Automatic Node Title setter Subscriber based on SBF metadata 

### ISSUE THREAD

**Issue by DiegoPino** [esmero/strawberryfield#55]
# What is needed?

We want to allow users to hide the Node Title widget/Field during ingest/edit completely and use, as source for the required node->title a value coming from SBF.
To accomplish so, and following our own way of coding we want to generate an Event Pre Save Subscriber (extending one of our base classes) that in the absence of such Node property sets its value from the SBF metadata. Drupal, strangely enough allows a Title field to be hidden in a Form Mode, but can not handle a Node CRUD operation if the value is not there (White screen with a Constraint error).

This subscriber is quite basic, and will required, to be stronger additional logic coming from the webform_strawberryfield module to, in case of being hidden, but set (e.g edit) to unset the value, so this Subscriber can override it. But that is another ISSUE:

Side note: Drupal's Content Entity Labels/Titles are limited to 128 Characters, quite not suited for metadata, so we will apply a truncating function. Still, the SBF, longer and richer Title will be available and can be used for Solr Indexing and display if wanted.

@giancarlobi @mitchellkeaney @marlo-longley

**Comment by mitchellkeaney** [comment]
Hey @DiegoPino - please excuse my n00b understanding of this issue, but do I understand that is addressing the concern of how we will treat the "Title" field and how, when say, someone (presumably an admin user) makes an edit to the ADO's metadata title (vs. the display title) and how Archipelago will treat that?

Thanks!

**Comment by DiegoPino** [comment]
@mitchellkeaney sorry my friend for the late answer. Yes. To claridy. This issue is to address the fact that some people don't even want to see native Drupal form fields around when editing and ingesting. They would love to have a unified Webform experience =). Since Drupal's Node Title field (via a Drupal Field widget) is the only one we can not make "optional" because if we just hide it Drupal goes nuts and ends with a Blank page, we will solve the problem by "injecting" the value of one JSON/SBF Metadata keys into the NODE/DIGITAL OBJECT/ADO Title (also known as Entity Label) in a Pre Save event, behind curtains. Hope this explains it better.

**Comment by mitchellkeaney** [comment]
@DiegoPino yes, that answers my question, thank you!

**Comment by DiegoPino** [comment]
Solved via https://github.com/esmero/strawberryfield/commit/62eb7579d219ba1843392f5e7ff5e27ef3692ebc

**Comment by marlo-longley** [comment]
@DiegoPino that is awesome. Will be a crowd pleaser.
