### ISSUE TITLE
Add missing schema

### ISSUE THREAD

**Issue by marlo-longley** [esmero/strawberryfield#71]
## What is the issue?

Missing schema for strawberry_textarea widget.

This was the only missing schema I found directly related to the `strawberryfield` repo but we can leave open this issue until all the schema errors are resolved.

**Comment by DiegoPino** [comment]
Partially solved by https://github.com/esmero/strawberryfield/commit/21d900cb0f1b84f41dd3dfa56c24bf755ebeaf74

Lets give this a few more hours. I need to spin a machine. If no SBF related schema warnings appear will close as solved. Thanks

**Comment by DiegoPino** [comment]
Resolved
