### ISSUE TITLE
Extract basic File Metadata on File Persister Service and push as flavor

### ISSUE THREAD

**Issue by DiegoPino** [esmero/strawberryfield#86]
# What is this?

Basically a quick hack, don't do this at home kids for File Description extraction when dealing with ADOs/Archipelago Digital Objects with Small Binaries/not many Binaries and that don't have the luxury (yet) to have strawberry_runners doing all their cool ReactPHP Async background processing for you.

This adds a WIP Method to the filePersisterService that will process/move/to/tmp files, run exiftool and (UK) Pronom extraction (FIDO) and push back all the insane amount of data into the JSON.

# What is also needed?

- A check that says , hey! You are adding like 3 files, Ok, i can process in sync/realtime, but hey, those are 2000 pages of poetry and thoughts, no way i'm doing that, install/setup strawberry_runners for that, i will only do it for the first, 3? that are less than 100 Mbytes. OR so.

- Move Checksumming which runs on the main method into this ::getBaseFileMetadata() (oh.. you have not seen the pull yet.. well, linked down!)

- Add a Config Form for FIDO and EXIFTOOL. Future i want to use https://github.com/richardlehane/siegfried also

**Comment by DiegoPino** [comment]
@giancarlobi when you have a moment i would like to discuss the following:
- I have been testing EXIF extraction on files and wondering now, how efficient/useful it is to actually keep all around in the SBF. Even when 10 images, the number of elements can grow too much. Its not the size, but the fact that we have multiple levels, and to be honest, exif is already! carried around in the actual file, so wondering what elements (and how can be define/decide) are the ones we want to extract. Or we want to simply dump them directly into a file (like the flavors we did last year) and let solr deal with them? If so we need to finish that code (urgent)
-  FIDO is ok, quite fast and won't take too much space.

The question i have now is how we can measure performance and impact. It most of the times not a server issue, but a UI issue when using the webforms/ajax, and still i don't know if that is even an issue or not. But i want to be able to provide people with options.

**Comment by giancarlobi** [comment]
@DiegoPino it could be on wednesday, is it ok for you?

**Comment by DiegoPino** [comment]
@giancarlobi i have a strange week ahead. Too many calls and teaching and meetings and development 😢 . Maybe we can start simply in the chat here and figure out a call closer to Friday? Also good afternoon for you!

**Comment by giancarlobi** [comment]
@DiegoPino ok to start here and eventually a call on Friday. I'm little busy so I'll start posting here tomorrow. Have a nice day, amigo

**Comment by DiegoPino** [comment]
@giancarlobi i totally understand your workload so won't demand more from you that you share your thoughts and ideas here. Thanks!

**Comment by DiegoPino** [comment]
In the meantime: https://exiftool.org/TagNames/index.html
This is the list of all Tags (known). This are the ones i feel are safe to extract

AS a way of limiting the number of EXIF tags ( i got an image with over 300 today) i plan on using this

exiftool -json -q -a -gps:all -Common "-gps*" -xmp:all  -ImageWidth -ImageHeight -Canon -Nikon-AllDates -pdf:all -MIMEType

**Comment by aksm** [comment]
Resolved by #87 and continued in #103.
